_ = require "underscore"
helper = require "../../core/helper/model"

module.exports = (bookshelf) ->
  bookshelf.Model.extend
    tableName: "_3DCartProducts"
    hasTimestamps: ['_createdAt', '_updatedAt']
  ,
    _.extend helper(bookshelf),
      buildTable: (table) ->
        table.increments()
        table.string("MFGID").nullable()
        table.string("ShortDescription").nullable()
        table.integer("ManufacturerID").nullable()
        table.specificType("DistributorList", "jsonb[]").nullable()
        table.dateTime("LastUpdate").notNullable()
        table.string("UserID").nullable()
        table.string("GTIN").nullable()
        table.specificType("CategoryList", "jsonb[]").nullable()
        table.boolean("NonTaxable").nullable()
        table.boolean("NotForSale").nullable()
        table.boolean("Hide").nullable()
        table.boolean("GiftCertificate").nullable()
        table.boolean("HomeSpecial").nullable()
        table.boolean("CategorySpecial").nullable()
        table.boolean("NonSearchable").nullable()
        table.boolean("GiftWrapItem").nullable()
        table.decimal("ShipCost", 10, 2).defaultTo(0)
        table.decimal("Weight", 10, 2).defaultTo(0)
        table.decimal("Height", 10, 2).defaultTo(0)
        table.decimal("Width", 10, 2).defaultTo(0)
        table.decimal("Depth", 10, 2).defaultTo(0)
        table.boolean("SelfShip").nullable()
        table.boolean("FreeShipping").nullable()
        table.integer("RewardPoints").nullable()
        table.integer("RedeemPoints").nullable()
        table.boolean("DisableRewards").nullable()
        table.integer("StockAlert").nullable()
        table.integer("ReorderQuantity").nullable()
        table.string("InStockMessage").nullable()
        table.string("OutOfStockMessage").nullable()
        table.string("BackOrderMessage").nullable()
        table.string("WarehouseLocation").nullable()
        table.string("WarehouseBin").nullable()
        table.string("WarehouseAisle").nullable()
        table.string("WarehouseCustom").nullable()
        table.text("Description").nullable()
        table.text("Keywords").nullable()
        table.string("ExtraField1").nullable()
        table.string("ExtraField2").nullable()
        table.string("ExtraField3").nullable()
        table.string("ExtraField4").nullable()
        table.string("ExtraField5").nullable()
        table.text("ExtraField6").nullable()
        table.text("ExtraField7").nullable()
        table.text("ExtraField8").nullable()
        table.text("ExtraField9").nullable()
        table.text("ExtraField10").nullable()
        table.text("ExtraField11").nullable()
        table.text("ExtraField12").nullable()
        table.text("ExtraField13").nullable()
        table.specificType("FeatureList", "jsonb[]").nullable()
        table.specificType("PluginList", "jsonb[]").nullable()
        table.string("MainImageFile").nullable()
        table.text("MainImageCaption").nullable()
        table.string("ThumbnailFile").nullable()
        table.string("MediaFile").nullable()
        table.string("AdditionalImageFile2").nullable()
        table.text("AdditionalImageCaption2").nullable()
        table.string("AdditionalImageFile3").nullable()
        table.text("AdditionalImageCaption3").nullable()
        table.string("AdditionalImageFile4").nullable()
        table.text("AdditionalImageCaption4").nullable()
        table.specificType("ImageGalleryList", "jsonb[]").nullable()
        table.specificType("OptionSetList", "jsonb[]").nullable()
        table.specificType("AdvancedOptionList", "jsonb[]").nullable()
        table.specificType("RelatedProductList", "jsonb[]").nullable()
        table.specificType("UpSellingItemList", "jsonb[]").nullable()
        table.specificType("DiscountList", "jsonb[]").nullable()
        table.boolean("DoNotUseCategoryOptions").nullable()
        table.dateTime("DateCreated").notNullable()
        table.integer("ListingTemplateID").nullable()
        table.string("ListingTemplateName").nullable()
        table.integer("LoginRequiredOptionID").nullable()
        table.string("LoginRequiredOptionName").nullable()
        table.string("LoginRequiredOptionRedirectTo").nullable()
        table.integer("AllowAccessCustomerGroupID").nullable()
        table.string("AllowAccessCustomerGroupName").nullable()
        table.string("RMAMaxPeriod").nullable()
        table.string("TaxCode").nullable()
        table.string("DisplayText").nullable()
        table.decimal("MinimumQuantity", 10, 2).defaultTo(0)
        table.decimal("MaximumQuantity", 10, 2).defaultTo(0)
        table.boolean("AllowOnlyMultiples").nullable()
        table.boolean("AllowFractionalQuantity").nullable()
        table.string("QuantityOptions").nullable()
        table.boolean("GroupOptionsForQuantityPricing").nullable()
        table.boolean("ApplyQuantityDiscountToOptions").nullable()
        table.boolean("EnableMakeAnOfferFeature").nullable()
        table.string("MinimumAcceptableOffer").nullable()
        table.decimal("PriceLevel1", 10, 2).defaultTo(0)
        table.boolean("PriceLevel1Hide").nullable()
        table.decimal("PriceLevel2", 10, 2).defaultTo(0)
        table.boolean("PriceLevel2Hide").nullable()
        table.decimal("PriceLevel3", 10, 2).defaultTo(0)
        table.boolean("PriceLevel3Hide").nullable()
        table.decimal("PriceLevel4", 10, 2).defaultTo(0)
        table.boolean("PriceLevel4Hide").nullable()
        table.decimal("PriceLevel5", 10, 2).defaultTo(0)
        table.boolean("PriceLevel5Hide").nullable()
        table.decimal("PriceLevel6", 10, 2).defaultTo(0)
        table.boolean("PriceLevel6Hide").nullable()
        table.decimal("PriceLevel7", 10, 2).defaultTo(0)
        table.boolean("PriceLevel7Hide").nullable()
        table.decimal("PriceLevel8", 10, 2).defaultTo(0)
        table.boolean("PriceLevel8Hide").nullable()
        table.decimal("PriceLevel9", 10, 2).defaultTo(0)
        table.boolean("PriceLevel9Hide").nullable()
        table.decimal("PriceLevel10", 10, 2).defaultTo(0)
        table.boolean("PriceLevel10Hide").nullable()
        table.string("BuyButtonLink").nullable()
        table.string("ProductLink").nullable()
        table.string("Title").nullable()
        table.string("CustomFileName").nullable()
        table.string("RedirectLink").nullable()
        table.text("MetaTags").nullable()
        table.text("SpecialInstructions").nullable()
        table.boolean("AssignKey").nullable()
        table.boolean("ReUseKeys").nullable()
        table.specificType("SerialList", "jsonb[]").nullable()
        table.specificType("EProductList", "jsonb[]").nullable()
        table.specificType("SKUInfo", "jsonb").nullable()

        table.bigInteger("_uid").notNullable().unsigned() # native 3DCart id
        table.string("_avatarId").notNullable()
        table.dateTime("_createdAt").notNullable()
        table.dateTime("_updatedAt").notNullable()
        table.unique(["_uid", "_avatarId"], "_3dcartproducts__uid__avatarid_unique") # index name is optional; it's added here as workaround for a number "3" in the beginning of index name
